# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [5]:
v= np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [6]:
v.shape

(39,)

5. Print the type of the previous array in question 3

In [7]:
v.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [8]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Dell/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

7. Print the dimension of the array in question 3


In [9]:
v.ndim

1

8. Create a boolean array with all the True values

In [11]:
sample_arry = [True]
bool_arry = np.random.choice(sample_arr, size=10)
print('Numpy Array: ')
print(bool_arry)


Numpy Array: 
[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [18]:
x = np.array([[2, 4, 6], [6, 8, 10]])
print(x)
x.ndim

[[ 2  4  6]
 [ 6  8 10]]


2

10. Create a three dimensional array



In [21]:
x=np.arange(24).reshape(4,3,2)
print(x)
x.ndim


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [22]:
x = np.arange(13, 36)
print("Original")
print(x)
print("Reverse")
x = x[::-1]
print(x)


Original
[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
Reverse
[35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13]


12. Create a null vector of size 10 but the fifth value which is 1 

In [23]:
x = np.zeros(10)
print(x)
print("Update fiffth value to 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fiffth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [24]:
iden_mat=np.identity(3)
print('3x3 matrix:')
print(iden_mat)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [27]:
arr = np.array([1, 2, 3, 4, 5])
print("Original array elements")
print(arr)
print("Convert integer to float values values:")
print(arr.astype(float))


Original array elements
[1 2 3 4 5]
Convert integer to float values values:
[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [31]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr_result = np.multiply(arr1, arr2)

print(arr_result)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [32]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

comparison = arr1 == arr2 
equal_arrays = comparison.all() 
  
print(equal_arrays) 

False


17. Extract all odd numbers from arr with values(0-9)

In [34]:
a = np.array([0,1,2,3,4,5,6,6,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [38]:
a = np.array([0,1,2,3,4,5,6,6,7,8,9])
np.where(a % 2 == 1, -1, a) 

array([ 0, -1,  2, -1,  4, -1,  6,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [47]:
arr = np.arange(10)
print(arr)
print("replacing")

arr[5]=9
arr[6]=11
arr[7]=10
print(arr)


[0 1 2 3 4 5 6 7 8 9]
replacing
[ 0  1  2  3  4  9 11 10  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [49]:
x = np.ones((5,5))
print("Original array")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [59]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
np.where(a % 2 == 1, 12, a) 

array([[12,  2, 12],
       [ 4, 12,  6],
       [12,  8, 12]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [71]:
array1 = np.arange(12).reshape(4,3)
print(array1)
array1[0:1]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[0, 1, 2]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [72]:
array1 = np.arange(12).reshape(4,3)
print(array1)
array1[0:2]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[0, 1, 2],
       [3, 4, 5]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [77]:
array1 = np.arange(12).reshape(4,3)

array1[3:6]

array([[ 9, 10, 11]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [78]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.37923492 0.32104766 0.07888737 0.74160839 0.85132203 0.51491551
  0.59459199 0.3350455  0.94613498 0.11517831]
 [0.96655168 0.16104404 0.19742945 0.09485322 0.86726593 0.28440094
  0.92350146 0.261181   0.94648368 0.5746387 ]
 [0.67800539 0.82200288 0.73384098 0.40832644 0.08798949 0.32281899
  0.49363282 0.37080731 0.46860648 0.90490225]
 [0.29150653 0.01975369 0.09502555 0.7235638  0.80602769 0.00412103
  0.18913101 0.21223549 0.90820759 0.83186853]
 [0.77981693 0.77575182 0.58237767 0.20477892 0.28555621 0.89131991
  0.17015611 0.1376182  0.24273367 0.50711661]
 [0.81084908 0.67077361 0.10955695 0.96709496 0.80419642 0.45017745
  0.88764669 0.3091696  0.96715078 0.98135072]
 [0.03424611 0.78415348 0.84820168 0.06074222 0.72878908 0.81473542
  0.0584642  0.88086873 0.24564561 0.07713876]
 [0.43240483 0.71183439 0.74017919 0.96090576 0.8867402  0.12760261
  0.18874475 0.47362395 0.95029949 0.67998226]
 [0.95417777 0.02036014 0.54509391 0.72467642 0.46855126 0.11231

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [90]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a,b[2,4])
print(c)
 

In [93]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
np.where(names[4])

(array([0], dtype=int64),)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [98]:
np.random.randint(1, 11, 15).reshape(5, 3)

array([[ 3,  1,  1],
       [ 5,  5,  2],
       [ 7,  1, 10],
       [ 6,  3,  3],
       [ 5,  4,  6]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [103]:
a=np.random.randint(1, 11, 16).reshape(2,2, 4)
a

array([[[2, 7, 8, 6],
        [4, 8, 6, 1]],

       [[1, 1, 5, 2],
        [1, 9, 8, 8]]])

33. Swap axes of the array you created in Question 32

In [104]:
arr = np.arange(9).reshape(3,3)
arr
temp = arr[:,0].copy() # temporary variable
arr[:,0], arr[:,1] = arr[:,1], temp
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [105]:
x = np.random.random((12))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[0.06353719 0.3437781  0.23520085 0.25147376 0.88534852 0.50038916
 0.17987126 0.1815238  0.11847266 0.3748378  0.34882821 0.68956546]
Minimum and Maximum Values:
0.06353719100975375 0.8853485193362167


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [109]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a=np.unique(names)
a

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [124]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(a,b)
b = np.delete(b,[0,1,2,3,4])
print(a,b)

[1 2 3 4 5] [5 6 7 8 9]
[1 2 3 4 5] []


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [136]:
x = np.array([[34,43,73],[82,22,12],[53,94,66]])

y = np.array([[10,10,10]])
print(x,y)
print("after delet colum")
x = np.delete(x, 1, 1)
y = np.delete(y, 1, 1)
print(x,y)
print("after insert colum")
y = np.array([[13], [20],[70]])
print(np.append(x, y, axis=1))


[[34 43 73]
 [82 22 12]
 [53 94 66]] [[10 10 10]]
after delet colum
[[34 73]
 [82 12]
 [53 66]] [[10 10]]
after insert colum
[[34 73 13]
 [82 12 20]
 [53 66 70]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [137]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(np.add(np.dot(x, y), 0))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [145]:
x = np.random.random((20))
y=np.array([3,2])
print(x,y) 


[0.5611657  0.97407772 0.83509857 0.48704454 0.19516834 0.04648597
 0.32122585 0.08701936 0.98886411 0.26002047 0.10025507 0.15022871
 0.0528367  0.73524732 0.91621828 0.33539747 0.16949688 0.58191933
 0.23566155 0.5668115 ] [3 2]
