# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
a_1d_array = np.array([0,1, 2, 3, 4,5,6,7,8,9])
print(a_1d_array)
reshaped_to_2d = np.reshape(a_1d_array, (-1, 2))
print(reshaped_to_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 1, 1, 1, 1])
np.vstack((x,y))


array([[0, 1, 2, 3, 4],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [14]:
x = np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
y = np.array( [5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
np.vstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [19]:
b=np.arange(15).reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [34]:

a=np.arange(25).reshape(5,5)
print(a)
print ("Square Value of a : \n", np.square(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Square Value of a : 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [39]:
a=np.arange(30).reshape(5,6)
print(a)
print("mean of a : ", np.mean(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
mean of a :  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [41]:
a=np.arange(30).reshape(5,6)
print(a)
print("std of a : ", np.std(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
std of a :  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [44]:
a=np.arange(30).reshape(5,6)
print(a)

print("median of a : ", np.median(a)) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
median of a :  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [47]:
a=np.arange(30).reshape(5,6)
print(a)
print("", end ='\n\n')
print(a.transpose()) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [51]:
a=np.arange(16).reshape(4,4)
print(a)
trace = np.trace(a) 
  
  
print("\nTrace of given 4X4 matrix:") 
print(trace) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Trace of given 4X4 matrix:
30


## Question:13

### Find the determinant of the previous array in Q12?

In [54]:
a=np.arange(16).reshape(4,4)
print(a)
det = np.linalg.det(a) 
  
print("\nDeterminant of given 4X4 matrix:") 
print(int(det)) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Determinant of given 4X4 matrix:
0


## Question:14

### Find the 5th and 95th percentile of an array?

In [55]:
arr = [20, 2, 7, 1, 34]
print("arr : ", arr) 
print("5th percentile of arr : ", 
       np.percentile(arr, 5))
print("95th percentile of arr : ",
       np.percentile(arr, 95))


arr :  [20, 2, 7, 1, 34]
5th percentile of arr :  1.2000000000000002
95th percentile of arr :  31.2


## Question:15

### How to find if a given array has any null values?

In [57]:

a = np.array([5, 2, 8, 9, 3, np.nan,2, 6, 1, np.nan]) 
  
b = a[np.logical_not(np.isnan(a))] 
   
print("original 1D array                    ->", a) 
print("1D array after removing nan values   ->", b) 
print() 
  
c = np.array([[6, 2, np.nan], [2, 6, 1], 
                 [np.nan, 1, np.nan]]) 

d = c[np.logical_not(np.isnan(c))] 
  
print("Original 2D array   ->") 
print(c) 
print("2D array converted to 1D after removing nan values   ", d)

original 1D array                    -> [ 5.  2.  8.  9.  3. nan  2.  6.  1. nan]
1D array after removing nan values   -> [5. 2. 8. 9. 3. 2. 6. 1.]

Original 2D array   ->
[[ 6.  2. nan]
 [ 2.  6.  1.]
 [nan  1. nan]]
2D array converted to 1D after removing nan values    [6. 2. 2. 6. 1. 1.]
