# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [2]:
#type your code here
import numpy as np


2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [3]:
#type your code here
cupcakes=np.array([2,0.75,2,1,0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [4]:
#type your code here
import csv


In [5]:
with open ("recipes.csv","r") as file:
    recipes=csv.reader(file)
    for recipe in recipes:
        print(recipe)

['2', '0.75', '2', '1', '0.5']
['1', '0.125', '1', '1', '0.125']
['2.75', '1.5', '1', '0', '1']
['4', '0.5', '2', '2', '0.5']


In [59]:
recipes = np.genfromtxt('recipes.csv', delimiter=',')
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.



Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [6]:
#type your code here
Cupcakes=np.array(['2', '0.75', '2', '1', '0.5'])
Pancake=np.array(['1', '0.125', '1', '1', '0.125'])
Cookie=np.array(['2.75', '1.5', '1', '0', '1'])
Bread=np.array(['4', '0.5', '2', '2', '0.5'])

print (Cupcakes,Pancake,Cookie,Bread)

print("cupcakes =" ,f" recipe cups of flour {cupcakes[0]},Cups of Sugar {cupcakes[1]} ,Eggs {cupcakes[2]}, Cups of Milk {cupcakes[3]}, Cups of Butter {cupcakes[4]} ")
print("Pancake =" ,f" recipe cups of flour {Pancake[0]},Cups of Sugar {Pancake[1]} ,Eggs {Pancake[2]}, Cups of Milk {Pancake[3]}, Cups of Butter {Pancake[4]} ")
print("Cookie =" ,f" recipe cups of flour {Cookie[0]},Cups of Sugar {Cookie[1]} ,Eggs {Cookie[2]}, Cups of Milk {Cookie[3]}, Cups of Butter {Cookie[4]} ")
print("Bread =" ,f" recipe cups of flour {Bread[0]},Cups of Sugar {Bread[1]} ,Eggs {Bread[2]}, Cups of Milk {Bread[3]}, Cups of Butter {Bread[4]} ")

['2' '0.75' '2' '1' '0.5'] ['1' '0.125' '1' '1' '0.125'] ['2.75' '1.5' '1' '0' '1'] ['4' '0.5' '2' '2' '0.5']
cupcakes =  recipe cups of flour 2.0,Cups of Sugar 0.75 ,Eggs 2.0, Cups of Milk 1.0, Cups of Butter 0.5 
Pancake =  recipe cups of flour 1,Cups of Sugar 0.125 ,Eggs 1, Cups of Milk 1, Cups of Butter 0.125 
Cookie =  recipe cups of flour 2.75,Cups of Sugar 1.5 ,Eggs 1, Cups of Milk 0, Cups of Butter 1 
Bread =  recipe cups of flour 4,Cups of Sugar 0.5 ,Eggs 2, Cups of Milk 2, Cups of Butter 0.5 


In [63]:
cups=np.array(["recipe","flour","sugar","eggs","milk","butter"])
quantity=np.array([["cupcakes",'2',  '0.75',   '2',   '1',  ' 0.5'],["pancake",'1', '0.125', '1', '1', '0.125'],["cookie",'2.75', '1.5', '1', '0', '1'],["bread",'4', '0.5', '2', '2', '0.5']])


a=np.vstack((cups,quantity))
a



array([['recipe', 'flour', 'sugar', 'eggs', 'milk', 'butter'],
       ['cupcakes', '2', '0.75', '2', '1', ' 0.5'],
       ['pancake', '1', '0.125', '1', '1', '0.125'],
       ['cookie', '2.75', '1.5', '1', '0', '1'],
       ['bread', '4', '0.5', '2', '2', '0.5']], dtype='<U8')

5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [43]:
#type your code here
b=a[::,3:4]
b

array([['eggs'],
       ['2'],
       ['1'],
       ['1'],
       ['2']], dtype='<U8')

In [67]:
eggs = recipes[:,2]
eggs

array([2., 1., 1., 2.])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [77]:
#type your code here
one = recipes[(eggs == 1)]
one



7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [98]:
#type your code here

print("cupcakes",cupcakes)
print("---------------------------------------")

cookies = recipes[2,:]
print("cookies",cookies)


cupcakes [2.   0.75 2.   1.   0.5 ]
---------------------------------------
cookies [2.75 1.5  1.   0.   1.  ]


8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [99]:
#type your code here

double_batches_cake=cupcakes*2

print("double_batches_cake",double_batches_cake)

double_batches_cake [4.  1.5 4.  2.  1. ]


9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [102]:
#type your code here
grocery_list = cookies + double_batches_cake

print (grocery_list)

[6.75 3.   5.   2.   2.  ]
